### ISSUE TITLE
Export R6_txtq

### ISSUE THREAD

**Issue by ifellows** [wlandau/txtq#1]
It would be great if R6_txtq was exported. I am inheriting from it in another package (https://github.com/fellstat/ipc) and don't want to use `:::` as it is generally bad form. See https://github.com/fellstat/ipc/blob/master/R/text-file-source.R.

Are you open to this?

**Comment by wlandau** [comment]
Yes, good idea. Thank you.

**Comment by wlandau** [comment]
By the way, do you feel there is functionality from https://github.com/fellstat/ipc/blob/master/R/text-file-source.R you would like to see in`txtq` itself? I noticed you impose a maximum number of rows. Is that to prevent database files from getting too large? Perhaps `txtq` can impose an optional cap. Although, I do not yet know how to remove the head of a text file without rewriting all of the messages we want to keep. Maybe this is a drawback of choosing text files rather than an SQL database.

**Comment by ifellows** [comment]
Yes, I didn't want there to be a case where a shiny session could create a file of arbitrary size, as this would be a "bad thing." For `ipc`, all messages are always consumed at once. As a result, the file can just be deleted. The `.TxTQ` class just extends and `R6_txtq` and deletes the file on consumption if it is larger than a set size.

I think you are right about the limitation, however, it seems to me that most production systems would need to limit the queue size so that you don't get continuously growing files. In my opinion it would be a good feature to add.

**Comment by wlandau** [comment]
Interesting. I designed `txtq` for `drake`, which reinitializes the queues on each `make()`, so size was not a concern there.

At the very least, I think `txtq` should have a `$clean()` method to remove pushed messages (this may not be very efficient at first) and a `$reset()` method to delete all messages (more efficient). Would that help?

I am not sure yet about building in an automatic cap on the number of rows. It seems specific to use cases like yours. I can, however, clean up the internals a bit to make it easier to extend `txtq`s. A pull request is forthcoming.

**Comment by wlandau** [comment]
See #2, #3, and #4. With `$clean()`, `$reset()`, and cleaner code, it should be easier to extend `txtq` for your use case.

**Comment by wlandau** [comment]
Is there anything else you need? I am planning to submit this to CRAN tomorrow before I go on vacation for the next 2 weeks.

**Comment by ifellows** [comment]
ipc is sitting in CRAN incoming right now. I don’t think that these changes will break anything, but I’ll check.

These changes will definitely make the implementation on my side more elegant.

**Comment by wlandau** [comment]
`R CMD check --as-cran` passes cleanly on my machine with [ftp://cran.r-project.org/incoming/inspect/ipc_0.1.0.tar.gz](ftp://cran.r-project.org/incoming/inspect/ipc_0.1.0.tar.gz) and b07bf372ef84f45f530f0e52dc9570c499a69be1, and your tests cover 92.59% of the code lines in `R/text-file-source.R`. So it seems like we're okay.
