### ISSUE TITLE
Option to disable the lockfile

### ISSUE THREAD

**Issue by wlandau** [wlandau/txtq#18]
## Prework

- [x] Read and abide by `txtq`'s [code of conduct](https://github.com/wlandau/txtq/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/wlandau/txtq/issues), both open and closed.

## Description

Should help https://github.com/ropensci/drake/issues/1239 and https://github.com/ropensci/drake/issues/1232 and performance in cases where we use the `txtq` as a database instead of a message queue.

**Comment by pydupont** [comment]
Sounds good! Tell me if you need some tests to be performed on Linux

**Comment by wlandau** [comment]
Thought about it more and decided against it because it goes against the original intent of `txtq`. `txtq` is a message queue first and foremost, and usage of `txtq` as a message queue always requires a lockfile.

**Comment by wlandau** [comment]
Reopening in light of https://github.com/r-lib/filelock/issues/26. This seems the only way to solve instances of https://github.com/ropensci/drake/issues/1239.
