### ISSUE TITLE
is txtq nfs-safe?

### ISSUE THREAD

**Issue by r2evans** [wlandau/txtq#19]
## Prework

- [x] Read and abide by `txtq`'s [code of conduct](https://github.com/wlandau/txtq/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/wlandau/txtq/issues), both open and closed.

## Description

Hey Will, my apologies for asking-before-extensive-testing.

Is `txtq` NFS-safe?

(I believe) I understand its intent and it does a good job of cross-process coordination. Are there tests to determine suitability on non-lockfile-friendly filesystems such as NFS? I fear that a file can be created on one node and accessed on another before it is complete, where concurrent access cannot be controlled or even detected reliably.

The only mitigating technique that does not require significant underlying code is a maildir-approach, where files are created and filled in one directory (`./tmp/`) and then moved into the actual directory for operation (typically `./new/` or `./cur/`, in maildir-speak). The underlying *required* principle is atomicity, where "create-and-write" is not atomic, but "move-into-directory" is atomic: there is no risk during the move (rename) operation that the file will be read incompletely. (There is another atomic concern that maildir addresses: temp file creation, where NFS does not ensure atomic "detect if file exists and then create it".)

If `txtq` is *not* necessarily nfs-safe, I'm not suggesting a full maildir implementation, as that is more overhead than is needed, and I know you are sensitive to filesystem performance and timing. I'd be suggesting a maildir-like mechanism, where files are created safely in one location and then moved to the "real" location for `txtq`-functionality.

(This is related to https://github.com/richfitz/storr/issues/119#issuecomment-586400490, so I know that (a) performance is a concern for you, and (b) it's not as easy as it is in my head. Perhaps this is mostly a precautionary issue where if nfs-locking is a known concern or one that comes up in the future, then this might be an acceptable mitigation.)

Thanks

**Comment by wlandau** [comment]
Unfortunately, `txtq` is not NFS safe, as we found out the hard way in https://github.com/r-lib/filelock/issues/26. Perhaps https://github.com/r-lib/filelock/issues/1 will help. Other than that and documenting the limitation in the package, I doubt there is anything else we can do within the scope of `txtq`.

The maildir technique definitely has its uses, but I do not think it will help in this particular case. The approach you describe is about atomicity when it comes to creating files, but *locking* them is different. Locks can be unlocked and locked on files that already exist.

``` r
library(filelock)
tmp <- tempfile()
invisible(file.create(tmp))
file.exists(tmp)
#> [1] TRUE
l <- lock(tmp)
l
#> Lock on '/private/var/folders/k3/q1f45fsn4_13jbn0742d4zj40000gn/T/RtmpjvzNc8/file204a107d25ee'
unlock(l)
#> [1] TRUE
l
#> Unlocked lock on '/private/var/folders/k3/q1f45fsn4_13jbn0742d4zj40000gn/T/RtmpjvzNc8/file204a107d25ee'
file.exists(tmp)
#> [1] TRUE
```

<sup>Created on 2020-07-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by r2evans** [comment]
Is `unlock(l)` there supposed to remove the file? I don't understand the implication of the file still existing.

But I do understand the implication. Unfortunately, I can't think of a way of creating a lockfile using maildir-like mechanisms ... since there's no atomic move-but-fail-if-exists ... ergggg ...

Thanks

**Comment by wlandau** [comment]
Yeah, I doubt simple maildir would work on NFS because of the very file latencies we are worried about, and I suspect there's a lot more to regular file locking than maildir. As Gabor writes [here](https://github.com/r-lib/filelock#internals-on-unix), `filelock` uses [`fcntl`](https://www.gnu.org/software/libc/manual/html_node/File-Locks.html) or [`LockFileEx`](https://msdn.microsoft.com/en-us/library/aa365203.aspx), depending on the operating system. I am not sure atomic file locking will ever be fully reliable on NFS, but I will reopen this issue if there is an R package that does it reasonably well.
